language: r
cache: packages

branches:
  except:
    - gh-pages

script:
  - make html

## Packages not listed as a dependency in DESCRIPTION can be installed here. Equivalent to running install.packages in R.
r_packages:
 - tidyverse
 - kableExtra

## A list of packages to install directly from GitHub, using devtools::install_github from the devtools package. The package names here should be of the form user/repo
r_github_packages:
 - rladies/meetupr

notifications:
  email:
    on_success: change
    on_failure: change

deploy:
  provider: pages
  fqdn: www.rusergroup.co.za
  local_dir: _book
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master
